/// 倉庫マスタに手作業で分類・区分を付与したもの。仕向け先の判定に使う。
/// 区分: 日本国内 / 日本建機 / インドネシア建機 / ２輪 / その他 販売 / 国内管理用倉庫区分
/// 転記対象(エクセル No.5/6)は「日本国内」のみ。それ以外はBEE→BEI向けとして別集計。
table 倉庫分類
	lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f9a0b1

	column 倉庫番号
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f900b
		summarizeBy: none
		sourceColumn: 倉庫番号

		annotation SummarizationSetBy = Automatic

	column 倉庫名称
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f901b
		summarizeBy: none
		sourceColumn: 倉庫名称

		annotation SummarizationSetBy = Automatic

	column 分類
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f902b
		summarizeBy: none
		sourceColumn: 分類

		annotation SummarizationSetBy = Automatic

	column 区分
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f903b
		summarizeBy: none
		sourceColumn: 区分

		annotation SummarizationSetBy = Automatic

	partition 倉庫分類 = m
		mode: import
		source =
				let
				    ソース = Csv.Document(File.Contents("C:\\Users\\100172\\OneDrive - TBGR（Tokyo Boeki Holdings Corporation and group companies）\\ドキュメント\\GitHub\\siiretanka\\master\\倉庫分類.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    見出し = Table.PromoteHeaders(ソース, [PromoteAllScalars=true]),
				    型変換 = Table.TransformColumnTypes(見出し,{{"倉庫番号", type text},{"倉庫名称", type text},{"分類", type text},{"区分", type text}})
				in
				    型変換

	annotation PBI_ResultType = Table

