/// 倉庫マスタに手作業で分類・区分を付与したもの。材料の仕向け先の判定に使う。
/// 転記対象(エクセル No.5/6)は全仕向け合計。BEE/BEIの切り分けは購買主体であり
/// 倉庫ではない(BEE=TB播州電装が買った分がすべてNo.5/6。BEI自身の購買は別資料)。
/// 仕向け区分は分類から導出し、BEI側資料(2_部材値上がり_BEI)のセグメントに対応する:
/// HE-Exp→BEI向け HE輸出 / HE-DOM→BEI向け HE国内 / インドネシア２輪→BEI向け 二輪
/// 日本国内→日本国内 / 発注では使用していない→国内管理用 / 個社名→その他販売
/// 既定でどの仕向けも除外しない。内訳を見る軸として使う。
table 倉庫分類
	lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f9a0b1

	column 倉庫番号
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f900b
		summarizeBy: none
		sourceColumn: 倉庫番号

		annotation SummarizationSetBy = Automatic

	column 倉庫名称
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f901b
		summarizeBy: none
		sourceColumn: 倉庫名称

		annotation SummarizationSetBy = Automatic

	column 分類
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f902b
		summarizeBy: none
		sourceColumn: 分類

		annotation SummarizationSetBy = Automatic

	column 区分
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f903b
		summarizeBy: none
		sourceColumn: 区分

		annotation SummarizationSetBy = Automatic

	column 仕向け区分
		dataType: string
		lineageTag: 3d4e5f60-7182-4293-a4b5-c6d7e8f904b
		summarizeBy: none
		sourceColumn: 仕向け区分

		annotation SummarizationSetBy = Automatic

	partition 倉庫分類 = m
		mode: import
		source =
				let
				    ソース = Csv.Document(File.Contents("C:\\Users\\100172\\OneDrive - TBGR（Tokyo Boeki Holdings Corporation and group companies）\\ドキュメント\\GitHub\\siiretanka\\master\\倉庫分類.csv"),[Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    見出し = Table.PromoteHeaders(ソース, [PromoteAllScalars=true]),
				    型変換 = Table.TransformColumnTypes(見出し,{{"倉庫番号", type text},{"倉庫名称", type text},{"分類", type text},{"区分", type text},{"仕向け区分", type text}})
				in
				    型変換

	annotation PBI_ResultType = Table

